### ISSUE TITLE
Is Anything Valid?

### ISSUE THREAD

**Issue by jmaiher** [vCheckReport/vCheck-AD#1]
I've used multiple vChecks before for Exchange & vSphere - the ones created by Alan Renouf. 
I see his name mentioned in this repository as well. But there doesn't appear to be any valid substance for the AD vCheck. Is it or any of the other repositories under "vCheckReport" legit? It appears to me that all the files are simply HTML files and not PowerShell scripts. When renamed & opened as HTML, I'm seeing items from a user called Sneddo listed on each page.

**Comment by Sneddo** [comment]
You will see that this repo is part of the vCheckReport orginisation., this was formed by the major contributors of vCheck-vSphere to expand the scope of vCheck as a reporting framework. Originally, vCheck-vSphere was going to be moved to the org, but never happened.

vCheck-AD was going to be another example of use...but nobody ever really contributed anything. Not sure what you mean about the HTML files, the only repo that contains HTML is the vCheck website repo, everything else is Powershell.
